version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
  - package-ecosystem: "nuget"
    directory: "/code/"
    schedule:
      interval: "weekly"
